---
- name: Remove Packer.
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.file:
    dest: "{{ packer_bin_path }}/packer"
    state: absent
  tags: ["packages", "packer"]
  when: installed_result.rc == 0